config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'sessions', registrations: 'registrations' }
  root to: 'welcome#index'
  match 'examination(/*path)', to: 'static#index', via: :all
  namespace :admin do
    resources :dashboard, only: :index
    resources :users, only: [:index, :edit, :update]
    resources :candidates
    resources :examinations
    resources :licenses, only: [:new, :create, :update, :destroy] do
      put :undiscard, on: :member
    end
    resources :exams do
      member do
        get :assign
        get 'bulk_assign' => 'exams#bulk_assign'
        post 'bulk_assign' => 'exams#bulk_assign_post'
      end
    end
    resources :clients do
      get :examinations
      get :licenses
      member do
        get :candidates
        post :add_candidate
        post :add_user
        post :add_licence
      end
    end
    resources :tasks do
      resources :items, only: %i[index create destroy update] do
        member do
          patch :move_up
          patch :move_down
        end
      end
      member do
        get :settings
        patch :update_settings
        patch :toggle_published
      end
    end
    resources :items, only: [] do
      resources :options, only: %i[create update destroy] do
        patch :toggle_correct, on: :member
      end
    end
  end
end

app/views/admin/_task_list_row.html.slim
tr id=dom_id(task)
  td.align-middle
    i.fas.fa-fw.mr-1.fa-1x class=(task_icon_class(task))
  td
    = link_to edit_admin_task_path(task) do
      = task.name
    br
    small= t(task.type.underscore, scope: 'tasks.types')
  td= task.complexity
  td= task.score_method.humanize
  td
    = link_to toggle_published_admin_task_path(task), method: :patch, remote: :true, class: "badge badge rounded-capsule badge-soft-#{task.published? ? 'success' : 'warning' }" do
      - if task.published?
        i.fas.fa-eye.fa-fw.mr-1
        = t('published')
      - else
        i.fas.fa-eye-slash.fa-fw.mr-1
        = t('hidden')
  td.float-right
    = link_to '', class: 'btn btn-falcon-primary btn-sm' do
      i.fas.fa-eye.fa-fw
    = link_to edit_admin_task_path(task), class: 'btn btn-falcon-default btn-sm' do
      i.fas.fa-pencil-alt.fa-fw
    = link_to settings_admin_task_path(task), class: 'btn btn-falcon-default btn-sm' do
      i.fas.fa-cog.fa-fw
    - if policy(task).destroy?
      = link_to admin_task_path(task), class: 'btn btn-falcon-danger btn-sm', method: :delete, data: { confirm: 'Are you sure you want to remove task?' } do
        i.fas.fa-times.fa-fw