config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'sessions', registrations: 'registrations' }
  root to: 'welcome#index'
  match 'examination(/*path)', to: 'static#index', via: :all
  namespace :admin do
    resources :dashboard, only: :index
    resources :users, only: [:index, :edit, :update]
    resources :candidates
    resources :examinations
    resources :licenses, only: [:new, :create, :update, :destroy] do
      put :undiscard, on: :member
    end
    resources :exams do
      member do
        get :assign
        get 'bulk_assign' => 'exams#bulk_assign'
        post 'bulk_assign' => 'exams#bulk_assign_post'
      end
    end
    resources :clients do
      get :examinations
      get :licenses
      member do
        get :candidates
        post :add_candidate
        post :add_user
        post :add_licence
      end
    end
    resources :tasks do
      resources :items, only: %i[index create destroy update] do
        member do
          patch :move_up
          patch :move_down
        end
      end
      member do
        get :settings
        patch :update_settings
        patch :toggle_published
      end
    end
    resources :items, only: [] do
      resources :options, only: %i[create update destroy] do
        patch :toggle_correct, on: :member
      end
    end
  end
end

app/views/layouts/admin/_footer.html.slim
footer
  .row.no-gutters.justify-content-between.fs--1.mt-4.mb-3
    .col-12.col-sm-auto.text-center
      p.mb-0.text-600
        span.d-none.d-sm-inline-block
          br.d-sm-none
          = Date.today.year
          |  ©
          a href="https://edun.no"  Educate AS

app/views/layouts/admin/_header.html.slim
nav.navbar.navbar-light.navbar-glass.fs--1.font-weight-semi-bold.row.navbar-top.sticky-kit.navbar-expand
  button.navbar-toggler.collapsed aria-controls="navbarVerticalCollapse" aria-expanded="false" aria-label=("Toggle navigation") data-target="#navbarVerticalCollapse" data-toggle="collapse" type="button"
    span.navbar-toggler-icon
  a.navbar-brand.text-left.ml-3 href="/"
    .d-flex.align-items-center
      img.mr-2 alt="" src="#{image_path('edun-logo.svg')}" width="90" /
  #navbarNavDropdown1.collapse.navbar-collapse
    ul.navbar-nav.align-items-center.d-none.d-lg-block
      li.nav-item
        form.form-inline.search-box
          input.form-control.rounded-pill.search-input aria-label="Search" placeholder="Search..." type="search" /
          span.position-absolute.fas.fa-search.text-400.search-box-icon
    ul.navbar-nav.align-items-center.ml-auto
      li.nav-item.dropdown
        a#navbarDropdownNotification.nav-link.unread-indicator.px-0 aria-expanded="false" aria-haspopup="true" data-toggle="dropdown" href="#" role="button"
          span.fas.fa-bell.fs-2.fa-fw data-fa-transform="shrink-6"
        .dropdown-menu.dropdown-menu-right.dropdown-menu-card aria-labelledby="navbarDropdownNotification"
          .card.card-notification.shadow-none style=("max-width: 20rem")
            .card-header
              .row.justify-content-between.align-items-center
                .col-auto
                  h6.card-header-title.mb-0 Notifications
                .col-auto
                  a.card-link.font-weight-normal href="#"  Mark all as read
            .list-group.list-group-flush.font-weight-normal.fs--1
              .list-group-title NEW
              .list-group-item
                a.notification.notification-flush.bg-200 href="#!"
                  .notification-avatar
                    .avatar.avatar-2xl.mr-3
                      img.rounded-circle alt="" src="https://placekeanu.com/200/200" /
                  .notification-body
                    p.mb-1
                      strong Emma Watson
                      | replied to your comment : "Hello world 😍"
                    span.notification-time
                      span.mr-1 aria-label="Emoji" role="img" > 💬
                      | Just now
              .list-group-item
                a.notification.notification-flush.bg-200 href="#!"
                  .notification-avatar
                    .avatar.avatar-2xl.mr-3
                      .avatar-name.rounded-circle
                        span AB
                  .notification-body
                    p.mb-1
                      strong Albert Brooks
                      | reacted to
                      strong Mia Khalifa's
                      | status
                    span.notification-time
                      span.mr-1.fab.fa-gratipay.text-danger
                      | 9hr
              .list-group-title EARLIER
              .list-group-item
                a.notification.notification-flush href="#!"
                  .notification-avatar
                    .avatar.avatar-2xl.mr-3
                      img.rounded-circle alt="" src="https://placekeanu.com/200/150" /
                  .notification-body
                    p.mb-1 The forecast today shows a low of 20℃ in California. See today's weather.
                    span.notification-time
                      span.mr-1 aria-label="Emoji" role="img" > 🌤️
                      | 1d
            .card-footer.text-center.border-top-0
              a.card-link.d-block href="../pages/notifications.html"  View all
      - if current_user
        li.nav-item.dropdown= render 'layouts/admin/profile_menu'
      - else
        li.nav-item= link_to 'Sign in with Google', '/users/auth/google_oauth2', class: 'btn btn-primary'

app/views/layouts/admin/_profile_menu.html.slim
a#navbarDropdownUser.nav-link.pr-0 aria-expanded="false" aria-haspopup="true" data-toggle="dropdown" href="#" role="button"
  .avatar.avatar-xl
    img.rounded-circle alt="" src="https://placekeanu.com/200/200" /
.dropdown-menu.dropdown-menu-right.py-0 aria-labelledby="navbarDropdownUser"
  .bg-white.rounded-soft.py-2
    a.dropdown-item.font-weight-bold.text-warning href="#!"
      span= current_user.full_name
    .dropdown-divider
    = link_to t('.my_profile'), edit_user_registration_path, class: 'dropdown-item'
    .dropdown-divider
    a.dropdown-item href='#!'  Settings
    = link_to t('sign_out'), destroy_user_session_path, class: 'dropdown-item', method: :delete

app/views/layouts/admin/_sidebar.html.slim
nav.navbar.navbar-vertical.navbar-expand-xl.navbar-light.navbar-glass
  a.navbar-brand.text-left href="/"
    .d-flex.align-items-center
      img.mr-2 alt="" src="#{image_path('edun-logo.svg')}" style=("margin: 0 20px;") width="146" /
  #navbarVerticalCollapse.collapse.navbar-collapse
    ul.navbar-nav.flex-column
      li.nav-item
        a.nav-link.dropdown-indicator aria-controls="users" aria-expanded="false" data-toggle="collapse" href="#users" role="button"
          .d-flex.align-items-center
            span.nav-link-icon
              span.fas.fa-users
            span= t('users')
        ul#users.nav.collapse data-parent="#navbarVerticalCollapse"
          li.nav-item
            = link_to 'Manage users', admin_users_path, class: 'nav-link'
          li.nav-item
            = link_to 'Manage clients', admin_clients_path, class: 'nav-link'
          li.nav-item
            = link_to 'Manage candidates', admin_candidates_path, class: 'nav-link'

      li.nav-item
        a.nav-link.dropdown-indicator aria-controls="exams" aria-expanded="false" data-toggle="collapse" href="#exams" role="button"
          .d-flex.align-items-center
            span.nav-link-icon
              span.fas.fa-puzzle-piece
            span= t('exams')
        ul#exams.nav.collapse data-parent="#navbarVerticalCollapse"
          li.nav-item
            = link_to t('admin.tasks.new.new_task'), new_admin_task_path, class: 'nav-link text-success strong'
          li.nav-item
            = link_to t('admin.tasks.index.task_base'), admin_tasks_path, class: 'nav-link'
          li.nav-item
            = link_to t('exams'), admin_exams_path, class: 'nav-link'
          li.nav-item
            = link_to t('examinations'), admin_examinations_path, class: 'nav-link'
      li.nav-item
        a.nav-link.dropdown-indicator aria-controls="courses" aria-expanded="false" data-toggle="collapse" href="#courses" role="button"
          .d-flex.align-items-center
            span.nav-link-icon
              span.fas.fa-plug
            span Courses
        ul#courses.nav.collapse data-parent="#navbarVerticalCollapse"
          li.nav-item
            a.nav-link href="#"  All courses
          li.nav-item
            a.nav-link href="#"  Enrolments
    hr.border-300.my-2
    ul.navbar-nav.flex-column
      li.nav-item
        a.nav-link.dropdown-indicator aria-controls="documentation" aria-expanded="false" data-toggle="collapse" href="#documentation" role="button"
          .d-flex.align-items-center
            span.nav-link-icon
              span.fas.fa-book
            span Reports
        ul#documentation.nav.collapse data-parent="#navbarVerticalCollapse"
          li.nav-item
            a.nav-link href=""  Report1
          li.nav-item
            a.nav-link href=""  Report2
      li.nav-item
        a.nav-link href=""
          .d-flex.align-items-center
            span.nav-link-icon
              span.fas.fa-code-branch
            span Changelog
            span.badge.badge-pill.ml-2.badge-soft-primary v1.8.0

app/views/layouts/admin/admin.html.slim
doctype html
html
  head
    meta content=("text/html; charset=UTF-8") http-equiv="Content-Type" /
    meta charset="utf-8" /
    meta content="IE=edge" http-equiv="X-UA-Compatible" /
    meta content="width=device-width, initial-scale=1" name="viewport" /
    - if content_for? :title
      title= [yield(:title), 'edun.no'].join(' | ')
    - else
      title edun.no
    link href="#{image_path('favicons/apple-touch-icon.png')}" rel="apple-touch-icon" sizes="180x180" /
    link href="#{image_path('favicons/favicon-32x32.png')}" rel="icon" sizes="32x32" type="image/png" /
    link href="#{image_path('favicons/favicon-16x16.png')}" rel="icon" sizes="16x16" type="image/png" /
    link href="#{image_path('favicons/favicon.ico')}" rel=("shortcut icon") type="image/x-icon" /
    meta content="#{image_path('favicons/mstile-150x150.png')}" name="msapplication-TileImage" /
    meta content="#ffffff" name="theme-color" /
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_pack_tag 'application', media: 'all'
  body
    main#top.main
      .container
        = render 'layouts/admin/sidebar'
        .content
          = render 'layouts/admin/header'
          - if notice
            .alert.alert-success== notice
          - if alert
            .alert.alert-danger== alert
          = yield

          = render 'layouts/admin/footer'
    = javascript_pack_tag 'application'

app/views/layouts/admin/wide.html.slim
doctype html
html
  head
    meta content=("text/html; charset=UTF-8") http-equiv="Content-Type" /
    meta charset="utf-8" /
    meta content="IE=edge" http-equiv="X-UA-Compatible" /
    meta content="width=device-width, initial-scale=1" name="viewport" /
    - if content_for? :title
      title= [yield(:title), 'edun.no'].join(' | ')
    - else
      title edun.no
    link href="#{image_path('favicons/apple-touch-icon.png')}" rel="apple-touch-icon" sizes="180x180" /
    link href="#{image_path('favicons/favicon-32x32.png')}" rel="icon" sizes="32x32" type="image/png" /
    link href="#{image_path('favicons/favicon-16x16.png')}" rel="icon" sizes="16x16" type="image/png" /
    link href="#{image_path('favicons/favicon.ico')}" rel=("shortcut icon") type="image/x-icon" /
    meta content="#{image_path('favicons/mstile-150x150.png')}" name="msapplication-TileImage" /
    meta content="#ffffff" name="theme-color" /
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_pack_tag 'application', media: 'all'
  body
    main#top.main
      .container-fluid
        nav.navbar.navbar-vertical.navbar-expand-xl.navbar-light.navbar-glass
          a.navbar-brand.text-left href="/"
            .d-flex.align-items-center
              img.mr-2 alt="" src="#{image_path('edun-logo.svg')}" style=("margin: 0 20px;") width="146" /
          #navbarVerticalCollapse.collapse.navbar-collapse
            .flex-column
            - if content_for?(:filters)
              .card.mb-3
                .card-header
                  h5.mb-0= t('filter')
                .card-body
                  = yield(:filters)
        .content
          = render 'layouts/admin/header'
          - if notice
            .alert.alert-success= notice
          - if alert
            .alert.alert-danger= alert
          = yield

          = render 'layouts/admin/footer'
    = javascript_pack_tag 'application'