config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'sessions', registrations: 'registrations' }
  root to: 'welcome#index'
  match 'examination(/*path)', to: 'static#index', via: :all
  namespace :admin do
    resources :dashboard, only: :index
    resources :users, only: [:index, :edit, :update]
    resources :candidates
    resources :examinations
    resources :licenses, only: [:new, :create, :update, :destroy] do
      put :undiscard, on: :member
    end
    resources :exams do
      member do
        get :assign
        get 'bulk_assign' => 'exams#bulk_assign'
        post 'bulk_assign' => 'exams#bulk_assign_post'
      end
    end
    resources :clients do
      get :examinations
      get :licenses
      member do
        get :candidates
        post :add_candidate
        post :add_user
        post :add_licence
      end
    end
    resources :tasks do
      resources :items, only: %i[index create destroy update] do
        member do
          patch :move_up
          patch :move_down
        end
      end
      member do
        get :settings
        patch :update_settings
        patch :toggle_published
      end
    end
    resources :items, only: [] do
      resources :options, only: %i[create update destroy] do
        patch :toggle_correct, on: :member
      end
    end
  end
end

app/models/examination.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: examinations
#
#  id                  :bigint           not null, primary key
#  exam_id             :bigint
#  expires_at          :datetime
#  total_score         :integer          default(0), not null
#  total_time_spent    :integer          default(0), not null
#  status              :integer          default("pending")
#  meta                :jsonb            not null
#  discarded_at        :datetime
#  created_at          :datetime         not null
#  updated_at          :datetime         not null
#  user_id             :bigint
#  client_candidate_id :bigint
#

class Examination < ApplicationRecord
  has_paper_trail
  include Discard::Model

  belongs_to :exam
  belongs_to :client_candidate
  has_many :examination_tasks, dependent: :destroy
  delegate :client, to: :client_candidate, allow_nil: true
  delegate :candidate, to: :client_candidate, allow_nil: true

  store_accessor :meta, %i[comment]
  enum status: { pending: 0, in_progress: 1, completed: 2, pending_review: 3, reviewed: 4 }
  scope :by_examiner, ->(id) { where('examinations.user_id = ?', id) if id.present? }

  validates :exam, :client_candidate, presence: true
  validates :total_time_spent, numericality: { greater_than_or_equal_to: 0, allow_nil: true }
  validates :total_score, numericality: { greater_than_or_equal_to: 0, allow_nil: true }

  def total_time_spent_human
    ChronicDuration.output(total_time_spent, format: :short, units: 2, limit_to_hours: true)
  end

  def total_time_spent_human=(value)
    self.total_time_spent = ChronicDuration.parse(value.to_s) || 0
  end
end

app/controllers/admin/examinations_controller.rb
# frozen_string_literal: true

module Admin
  class ExaminationsController < AdminController
    before_action :authorize_action
    layout :resolve_layout

    def resolve_layout
      case action_name
      when 'index'
        'admin/wide'
      else
        'examiner/clean'
      end
    end

    def index
      search_form = scope.ransack(params[:q])
      examinations = search_form.result(distinct: true)
      render :index, locals: { examinations: examinations.kept.paginate(page: params[:page]), search_form: search_form }
    end

    def show
      authorize_action(examination)
      examiners = User.active_options_for_select(User.where(role: %w[examiner admin]))
      render :show, locals: { examination: examination, examiners: examiners }
    end

    def edit
      authorize_action(examination)
      render :edit, locals: { examination: examination }
    end

    def new
      examination = Examination.new
      render :new, locals: { examination: examination }
    end

    def create
      examination = Examination.create(examination_params)
      respond_to do |format|
        if examination.save
          format.html do
            redirect_to admin_client_examinations_path(examination.client), notice: 'Examination was successfully created.'
          end
        else
          format.html { render :new, locals: { examination: examination }, status: :unprocessable_entity }
        end
      end
    end

    def update
      authorize_action(examination)
      if examination.update(examination_params)
        redirect_to admin_examination_path(examination), notice: t('.examination_updated_html')
      else
        render :show, locals: { examination: examination }, status: :unprocessable_entity
      end
    end

    def destroy
      authorize_action(examination)
      examination.discard
      respond_to do |format|
        format.html { redirect_to admin_examinations_path, notice: 'The examination was successfully removed.' }
      end
    end

    private

    def examination
      @examination ||= scope.find(params[:id])
    end

    def authorize_action(record = Examination)
      authorize record, "#{action_name}?", policy_class: policy_class
    end

    def policy_class
      Admin::ExaminationPolicy
    end

    def scope
      policy_scope(Examination, policy_scope_class: Admin::ExaminationPolicy::Scope)
    end

    def examination_params
      params.require(:examination).permit(:client_candidate_id, :exam_id, :expires_at, :comment, :user_id)
    end
  end
end

app/views/admin/examinations/_form.html.slim
- if exam.errors.any?
  .alert.alert-warning#error_explanation
    h5
      = t('count_error_message_model', count: exam.errors.count, model: exam.model_name.human)
    ul
      - exam.errors.full_messages.each do |message|
        li= message
.row
  .col-lg-6
    .form-group
      = f.label :name, t('name')
      = f.text_field :name, class: 'form-control'
      = error_for f.object, :name
  .col-lg-6
    = f.label :price, t('admin.exams.new.default_price')
    .input-group
      .input-group-prepend
        span.input-group-text= t('nok')
      = f.text_field :price, class: 'form-control'
      = error_for f.object, :price
  .col-lg-6
    .form-group
      = f.label :max_time, t('admin.exams.new.maximum_time')
      = f.text_field :max_time, class: 'form-control', placeholder: 'Ex. 45 mins', value: ChronicDuration.output(exam.max_time || 0)
      = error_for f.object, :max_time
  .col-lg-6
    .form-group
      = f.label :max_tasks, t('admin.exams.new.maximum_tasks')
      = f.number_field :max_tasks, class: 'form-control'
      = error_for f.object, :max_tasks
.row
  .col-lg-6
    .form-group
      label= t('result_type_label')
      - Exam.result_types.keys.each do |rt|
        .custom-control.custom-radio
          = f.radio_button :result_type, rt, class: 'custom-control-input'
          = f.label "result_type_#{rt}".to_sym, rt.humanize, class: 'custom-control-label'
  .col-lg-6
    .form-group
      label= t('task_algorithm')
    - Exam.algorithms.keys.each do |a|
      .custom-control.custom-radio
        = f.radio_button :algorithm, a, class: 'custom-control-input'
        = f.label "algorithm_#{a}".to_sym, a.humanize, class: 'custom-control-label'
  .col-lg-12
    .form-group
      .custom-control.custom-switch
        = f.check_box :published, class: 'custom-control-input'
        = f.label :published, t('publish_exam'), class: 'custom-control-label'

  .col-12.d-flex.mt-3
    = f.submit t('save'), class: 'btn btn-primary mr-1'
    = link_to t('back'), admin_exams_path, class: 'btn btn-secondary mr-1'

app/views/admin/examinations/_list.html.slim
= will_paginate examinations
#examinations_list.bg-light
  table.table.thead-light.table-hover.table-condensed
    thead
      tr
        th= t('name')
        th= t('client')
        th= t('status')
        th= t('time_spent')
        th= t('score')
        th= t('actions')
    tbody
      - examinations.each do |examination|
        tr
          td= link_to examination.candidate.full_name, edit_admin_candidate_path(examination.candidate)
          td= link_to examination.client.name, admin_client_path(examination.client)
          td= examination_status_tag(examination)
          td= examination.total_time_spent_human
          td= examination.total_score
          td
            - if examination.completed? && policy(examination).show?
              = link_to admin_examination_path(examination), class: 'btn btn-falcon-primary btn-sm' do
                = t('.score')
            - elsif policy(examination).destroy?
              = link_to admin_examination_path(examination), class: 'btn btn-falcon-danger btn-sm', method: :delete, data: { confirm: 'Are you sure you want to remove examination?' } do
                i.fas.fa-times.fa-fw

app/views/admin/examinations/index.html.slim
- content_for :title do
  = t('examinations')
.card.mb-3
  .card-header
    .d-flex.justify-content-between
      h4.mb-0= t('examinations')
    = link_to new_admin_examination_path, class: 'card-link' do
      = t('.assign_exam_to_candidate')
      i.fas.fa-chevron-right.fa-fw
.card.mb-3
  .card-header
    h5= t('admin.clients.examinations.count_examinations', count: examinations.total_entries)

  = render partial: 'admin/examinations/list', locals: { examinations: examinations }

- content_for(:filters) do
  = search_form_for search_form, url: admin_examinations_path, method: :get, enforce_utf8: false do |f|
    .form-group
      = f.label t('admin.examinations.new.select_client')
      = f.select :client_candidate_client_id_eq, options_from_collection_for_select(Client.all, :id, :name, params.dig(:q, :client_candidate_client_id_eq)), { include_blank: '' }, class: 'select2 form-control'

    .form-group
      = f.label t('status')
      = f.select :status_eq, options_for_select(Examination.statuses, params.dig(:q, :published_true)), { include_blank: '  ' }, class: 'select2 form-control bg-white'

    .form-group
      = submit_tag t('filter'), class: 'btn btn-falcon-default'

app/views/admin/examinations/new.html.slim
- content_for :title do
  = t('admin.exams.bulk_assign_form.assign_exam_to_candidates')

.card
  .card-header
    h5.mb-0= t('admin.exams.bulk_assign_form.assign_exam_to_candidates')
  .card-body
    = form_for examination, url: admin_examinations_path, html: { id: 'examination_form' }, method: :post do |f|
      - if examination.errors.any?
        .alert.alert-warning#error_explanation
          h5
            = t('count_error_message_model', count: examination.errors.count, model: examination.model_name.human)
          ul
            - examination.errors.full_messages.each do |message|
              li= message
      .row
        .col-lg-6
          .form-group
            = f.select :exam_id, options_from_collection_for_select(Exam.all, :id, :name), { prompt: t('.select_exam') }, class: 'select2 form-control'
          .form-group
            = f.select :client_candidate_id, options_from_collection_for_select(ClientCandidate.all, :id, lambda { |cc| "#{cc.candidate.full_name} (#{cc.client.name})" }), { prompt: t('.select_candidate') }, class: 'select2 form-control'
          .form-group
            = f.text_field :expires_at, class: 'form-control datetimepicker', data: { options: { dateFormat: 'Y-m-d' } }, placeholder: 'Exam link expiry date'


        .col-12.d-flex.mt-3
          = f.submit 'Assign now', class: 'btn btn-primary mr-1'
          = link_to t('back'), admin_exams_path, class: 'btn btn-secondary mr-1'

app/views/admin/examinations/show.html.slim
- content_for :title do
  = t('.examination_candidate', name: examination.candidate.full_name)

.card.mb-3
  .card-header
    h3.mb-0= examination.exam.name
  .card-body
    .row.justify-content-between.align-items-center
      .col
        h6.text-500= t('assigned_to') + ': '
        h5= examination.candidate.full_name
        p.fs--1
          = t('ssn') + ': '
          = examination.candidate.ssn
          br
          = t('admin.users.list.client') + ': '
          = link_to examination.client.name, admin_client_path(examination.client)
        p.fs--1
          = examination.candidate.email
          br/
          = examination.candidate.mobile
      .col-sm-auto.ml-auto
        .table-responsive
          table.table.table-sm.table-borderless.fs--1
            tbody
              tr
                th.text-sm-right Examination ID
                td= examination.id
              tr
                th.text-sm-right Examination Date:
                td= Date.today
              tr
                th.text-sm-right Time spent
                td= examination.total_time_spent_human
              tr.alert-success.font-weight-bold
                th.text-sm-right Score
                td 350 / 549

- Task.all.each_with_index do |task, index|
  .card.mb-0
    .card-body.fs--1.border-top.border-200.p-0
      .row.border-bottom.border-200.hover-actions-trigger.hover-shadow.py-2.px-1.mx-0 data-href="../email/email-detail.html"
        .btn-group.btn-group-sm.hover-actions.r-0.mr-3
          = link_to '', class: 'btn btn-light' do
            i.fas.fa-cog.fa-fw
            = 'Set score'
        .col-auto.d-none.d-sm-block
          .d-flex.bg-white
            = index + 1
        .col.col-md-9.col-xxl-10
          .row
            .col-md-4.col-xl-5.col-xxl-2.pl-md-0.mb-1.mb-md-0
              .media
                .media-body.ml-2
                  = link_to '', class: 'font-weight-bold stretched-link inbox-link' do
                    = task.name
            .col
              = link_to '', class: 'd-block inbox-line font-weight-bold' do
                span.font-weight-bold= task.title
        .col-auto.ml-auto.d-flex.flex-column.justify-content-between
          - if examination.total_score
            span.badge.badge-soft-success.badge-pill.ml-2 Pending
          - else
            span.font-weight-bold 95%
.card.mt-3
  .card-header
    h4= t('.examination_evaluation')
  .card-body
    #skills_results
      table.table.table-bordered.bg-white
        thead
          tr.fs--1
            th Skill
            th Tasks
            th Score
            th Result
            th Level
        tbody
          - Skill.all.each do |skill|
            tr
              td= skill.name
              td 56
              td 89%
              td 3 of 19
              td
                input.form-control.form-control-sm placeholder="Price" type="text" value="$0.00" /

  .card-body
    = form_for [:admin, examination], html: { id: 'examination_form' }, method: :put do |f|
      .row
        .col-lg-12
          .form-group
            = f.label t('comment')
            = f.text_area :comment, rows: "7", class: 'form-control', placeholder: 'Enter your evaluation here'
          .form-group
            = f.select :user_id, options_for_select(examiners),
                    { prompt: t('.select_examiner') },
                    class: 'select2 form-control question'
        .col-12.d-flex.mt-3
          = f.submit t('save_changes'), class: 'btn btn-primary mr-1'
          = link_to t('back'), admin_examinations_path, class: 'btn btn-light btn-sm'