config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'sessions', registrations: 'registrations' }
  root to: 'welcome#index'
  match 'examination(/*path)', to: 'static#index', via: :all
  namespace :admin do
    resources :dashboard, only: :index
    resources :users, only: [:index, :edit, :update]
    resources :candidates
    resources :examinations
    resources :licenses, only: [:new, :create, :update, :destroy] do
      put :undiscard, on: :member
    end
    resources :exams do
      member do
        get :assign
        get 'bulk_assign' => 'exams#bulk_assign'
        post 'bulk_assign' => 'exams#bulk_assign_post'
      end
    end
    resources :clients do
      get :examinations
      get :licenses
      member do
        get :candidates
        post :add_candidate
        post :add_user
        post :add_licence
      end
    end
    resources :tasks do
      resources :items, only: %i[index create destroy update] do
        member do
          patch :move_up
          patch :move_down
        end
      end
      member do
        get :settings
        patch :update_settings
        patch :toggle_published
      end
    end
    resources :items, only: [] do
      resources :options, only: %i[create update destroy] do
        patch :toggle_correct, on: :member
      end
    end
  end
end

app/controllers/admin/licenses_controller.rb
# frozen_string_literal: true

module Admin
  class LicensesController < AdminController
    before_action :authorize_action

    def show; end

    def edit
      authorize_action(license)
      render :edit, locals: { license: license }
    end

    def new
      client = Client.find(params[:client_id]) if params[:client_id]
      license = License.new
      render :new, locals: { license: license, client: client }
    end

    def create
      license = License.create(license_params)
      respond_to do |format|
        if license.save
          format.html do
            redirect_to admin_client_path(license.client), notice: 'License was successfully created.'
          end
        else
          format.html { render :new, locals: { license: license }, status: :unprocessable_entity }
        end
      end
    end

    def update
      authorize_action(license)
      if license.update(license_params)
        redirect_to admin_license_path(license), notice: 'License was updated'
      else
        render :show, locals: { license: license }, status: :unprocessable_entity
      end
    end

    def destroy
      authorize_action(license)
      license.discard
      respond_to do |format|
        format.html { redirect_to admin_clients_path, notice: 'The license was successfully removed.' }
        format.js {}
      end
    end

    def undiscard
      License.with_discarded.discarded.find(params[:id]).undiscard
      respond_to do |format|
        format.js {}
      end
    end

    private

    def license
      @license ||= scope.find(params[:id])
    end

    def authorize_action(record = License)
      authorize record, "#{action_name}?", policy_class: policy_class
    end

    def policy_class
      Admin::LicensePolicy
    end

    def scope
      policy_scope(License, policy_scope_class: Admin::LicensePolicy::Scope)
    end

    def license_params
      params.require(:license).permit(:client_id, :licensable_id, :licensable_type, :amount, :expires_at)
    end
  end
end

app/views/admin/licenses/_license_fields.html.slim
- if defined?(client) && client.present?
  = f.hidden_field :client_id, value: client&.id
- else
  .form-group
    = f.select :client_id, options_from_collection_for_select(Client.kept, :id, :name), { prompt: t('admin.examinations.new.select_client') }, class: 'select2 form-control'
.form-group
  = f.select :licensable_id, options_from_collection_for_select(Exam.all, :id, :name), { prompt: t('admin.examinations.new.select_exam') }, class: 'select2 form-control'
  = f.hidden_field :licensable_type, value: 'Exam'
.form-group
  = f.number_field :amount, class: 'form-control', placeholder: t('amount')
.form-group
  = f.text_field :expires_at, class: 'form-control datetimepicker', data: { options: { dateFormat: 'Y-m-d' } }, placeholder: 'Exam link expiry date'

app/views/admin/licenses/_license_row.html.slim
tr id=dom_id(license)
  - if license.discarded?
    td.align-middle
      del.font-italic= license.licensable.name
    td.align-middle
      del.font-italic= license.amount
  - else
    td= license.licensable.name
    td= license.amount
  td.align-middle= license.created_at.to_date
  td.align-middle= license.expires_at
  td.align-middle= license.discarded_at&.to_date
  td.align-middle
    - if policy(license).destroy?
      - if license.discarded?
        = link_to undiscard_admin_license_path(license), class: 'btn btn-falcon-success btn-sm', method: :put, remote: true do
          i.fas.fa-undo.fa-fw
      - else
        = link_to admin_license_path(license), class: 'btn btn-falcon-danger btn-sm', method: :delete, data: { confirm: 'Are you sure you want to remove license?' }, remote: true do
          i.fas.fa-times.fa-fw

app/views/admin/licenses/_new.html.slim
= form_for license, url: admin_licenses_path, html: { id: 'license_form' }, method: :post do |f|
  .modal-header
    h5.mb-0= t('admin.clients.show.create_new_license')
  .modal-body
    = render 'license_fields', f: f, client: client
  .modal-footer
    button.btn.btn-falcon-default.btn-sm data-dismiss="modal" type="button"  Close
    = f.submit t('create'), class: 'btn btn-primary'

app/views/admin/licenses/destroy.js.erb
(function(){
    var elem = document.querySelector('#<%= dom_id(@license) %>');
    elem.parentNode.removeChild(elem);
})();

app/views/admin/licenses/new.html.slim
.card
  .card-header
    h5= t('admin.clients.show.create_new_license')
  .card-body
    = form_for license, url: admin_licenses_path, html: { id: 'license_form' }, method: :post do |f|
      - if license.errors.any?
        .alert.alert-warning#error_explanation
          h5= t('count_error_message_model', count: license.errors.count, model: license.model_name.human)
          ul
            - license.errors.full_messages.each do |message|
              li= message
      .row
        .col-lg-6
          = render 'license_fields', f: f, client: client
        .col-12.d-flex.mt-3
          = f.submit t('create'), class: 'btn btn-primary mr-1'
          = link_to t('back')
javascript:
  $('#edunModal .datetimepicker').each(function (index, value) {
      const $this = $(value);
      const options = $.extend({dateFormat: 'd/m/y'}, $this.data('options'));
      $this.attr('placeholder', options.dateFormat);
      $this.flatpickr(options);
  });

app/views/admin/licenses/new.js.erb
$("#edunModal .modal-content").html("<%= j render 'admin/licenses/new', license: License.new, client: client %>");

$('#edunModal select.select2').select2({
    theme: 'bootstrap4',
});
$('#edunModal .datetimepicker').each(function (index, value) {
    const $this = $(value);
    const options = $.extend({dateFormat: 'd/m/y'}, $this.data('options'));
    $this.attr('placeholder', options.dateFormat);
    $this.flatpickr(options);
});

app/views/admin/licenses/undiscard.js.erb
(function(){
    var $container = $('#<%= dom_id(@license) %>');
    $container.replaceWith('<%= j render 'admin/licenses/license_row', license: @license %>')
})();